version: '3'

networks:
  catalog:
    name: catalog

services:
  postgres:
    platform: linux/amd64
    image: postgres
    hostname: postgres
    networks: [ catalog ]
    container_name: catalog-postgres
    ports: [ 5433:5432 ]
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      start_period: 10s
