version: '3'

networks:
  shopping-cart:
    name: shopping-cart

services:
  postgres:
    platform: linux/amd64
    image: postgres
    hostname: postgres
    networks: [ shopping-cart ]
    container_name: shopping-cart-postgres
    ports: [ 5432:5432 ]
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      start_period: 10s
  liquibase:
    platform: linux/amd64
    image: liquibase/liquibase
    hostname: liquibase
    networks: [ shopping-cart ]
    container_name: shopping-cart-liquibase
    depends_on: [ postgres ]
    volumes: [ ./db:/liquibase/changelog ]
    command: "bash -c 'liquibase \
                       --url=jdbc:postgresql://postgres:5432/postgres \
                       --searchPath=/liquibase/changelog \
                       --changeLogFile=changelog.xml \
                       --username=postgres \
                       --password=postgres \
                       --databaseChangeLogTableName=_changelog \
                       --databaseChangeLogLockTableName=_changelog_lock \
                       update'"

