 FROM node as builder
 WORKDIR /app
 COPY . .
 RUN npm install --frozen-lockfile && \
     npm build

 FROM alpine as runner
 ENV NODE_ENV="development" \
     PORT=3000 \
     DB_LIMIT=50 \
     DB_POSTGRES="postgresql://postgres:postgres@localhost:5432/postgres"

RUN apk add --update nodejs
WORKDIR /app
COPY --from=builder /app/dist/ /app/
EXPOSE ${PORT}
CMD node index.js